---
#
# https://github.com/jcallaghan/esphome-config/blob/main/.readme/esph_ground_water.md
#
substitutions:
  system_name: ground_water
  friendly_name: Ground Water
  device_description: "Ultrasonic distance sensor fitted inside a tube with a table tennis ball measuring the depth of the water in our basement. /n Readme via https://github.com/jcallaghan/esphome-config/blob/main/.readme/esph_ground_water.md"

packages:
  device: !include devices/esp32_pico.yaml

sensor:      
      
  # https://www.esphome.io/components/sensor/ultrasonic.html
  - platform: ultrasonic
    id: height_value
    name: "ESPH ${friendly_name} Distance"   
    trigger_pin: GPIO2 # Green
    echo_pin: GPIO4 # Orange
    update_interval: 30s
    accuracy_decimals: 2
    #timeout: 2m
    #pulse_time: 30us
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 10
          send_first_at: 10

  # https://www.esphome.io/components/sensor/vl53l0x.html          