---
#
substitutions:
  system_name: hot_tub_energy
  friendly_name: Hot Tub Energy
  device_description: "Sonoff POWR2 powering my hot tub and used to monitor energy."

packages:
  device: !include devices/sonoff_pow_r2.yaml

esphome:
  on_boot:
    priority: -10  
    then:
      - switch.turn_on: device_relay