---
#
# https://github.com/jcallaghan/esphome-config/blob/main/.readme/esph_bedroom.md
#
substitutions:
  system_name: bedroom
  friendly_name: Bedroom
  device_description: "Pressure pad sensors placed under mattress to detect occupancy and presence in bed. Readme via https://github.com/jcallaghan/esphome-config/blob/main/.readme/esph_bedroom.md"

packages:
  device: !include devices/esp32_pico.yaml

binary_sensor:

  # Left pressure pad.
  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True      
    name: "ESPH ${friendly_name} Bed Left Occupied"
    id: bed_left
    device_class: occupancy

  # Right pressure pad.
  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP 
      inverted: True      
    name: "ESPH ${friendly_name} Bed Right Occupied"
    id: bed_right
    device_class: occupancy
