substitutions:
  system_name: upstairs
  friendly_name: Upstairs
  device_description: "Used to obtain temperature data from Xiaomi clock via bluetooth."

esphome:
  name: "esph_${system_name}"
  comment: ${device_description}
  platform: ESP32
  board: pico32

<<: !include .common/common.yaml

esp32_ble_tracker:

#esp32_ble_beacon:

sensor:

  - platform: xiaomi_lywsd02
    mac_address: "E7:2E:01:10:E0:4A"
    temperature:
      name: "ESPH ${friendly_name} Florence Bedroom Clock Temperature"
      unit_of_measurement: "°C"
    humidity:
      name: "ESPH ${friendly_name} Florence Bedroom Clock Humidity"
      unit_of_measurement: "%"